### ISSUE TITLE
upper bound and larger bound inconsistent with step sign

### ISSUE THREAD

**Issue by TaimurAdil** [monjurulkarim/xai-accident#1]
Executed this code through google colab and it's giving me this issue while generating train_sampler by calling MySampler class 

Currently, I used only one folder of framed images in both test and train 

![image](https://user-images.githubusercontent.com/3815509/150996976-42d5481d-63f5-4645-a855-b1db0388362f.png)

**Comment by monjurulkarim** [comment]
@TaimurAdil
It looks like your folder has 51 frames. Please know that each folder should contain total of 50 frames (eg. 0-49). I added the CCD dataset with extracted video frames in the readme file.
Please try with that dataset. Please feel free to let me know if you face additional difficulties.

**Comment by TaimurAdil** [comment]
You were right, the issue was with the dataset folder structure was not correct, the format of the dataset should be [https://drive.google.com/drive/folders/10ce-rLLpg2Hpymo_2XcHPouuHHq7kc0u](url)

Thanks for the prompt reply
